# Nginx FastCGI Cache: 	http://seravo.fi/2013/optimizing-web-server-performance-with-nginx-and-php
# More Caching: 		https://www.digitalocean.com/community/tutorials/how-to-setup-fastcgi-caching-with-nginx-on-your-vps
# Apache Bench Mac: 	http://kevify.com/2013/ab-on-mac/

fastcgi_cache_path /var/cache/nginx levels=1:2 keys_zone=MYAPP:100m inactive=60m;
fastcgi_cache_key "$scheme$request_method$host$request_uri";

server {
	listen 80;

	server_name example.com
	return 301 http://www.example.com$request_uri;
}

server {
	listen 80;

	server_name www.example.com;
	root /var/www/vhosts/www.example.com/httpdocs;
	index index.php;

	error_log /var/log/nginx/www.example.com-error.log error;

	charset utf-8;
	include h5bp/basic.conf;

	set $no_cache 0;

	if ($request_method = POST) {
		set $no_cache 1;
	}

	if ($query_string != '') {
		set $no_cache 1;
	}

	if ($request_uri ~* ^/admin) {
		set $no_cache 1;
	}

	add_header X-Cache $upstream_cache_status;

	location = /favicon.ico { log_not_found off; access_log off; }
	location = /robots.txt  { log_not_found off; access_log off; }

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;

		include fastcgi_params;
		fastcgi_param PHP_ADMIN_VALUE 'open_basedir=/var/www/vhosts/www.example.com';
		fastcgi_param PHP_ADMIN_VALUE 'include_path=/var/www/vhosts/www.example.com/httpdocs';

		fastcgi_cache MYAPP;
		fastcgi_cache_valid 200 60m;
		fastcgi_cache_bypass $no_cache;
		fastcgi_no_cache $no_cache;		
	}
}